### ISSUE TITLE
How to open graphical user interface?

### ISSUE THREAD

**Issue by wangyingjie55** [gpoo/ccfinderx#5]
I am a rookie in using ubuntu , I want to know how to open the graphical user interface? I do the 'make' command in GemX, but I don't know what to do next. Please help me. @gpoo

**Comment by wangyingjie55** [comment]
I do the command  "make run" under the dir GemX, but There was an error. Please tell me why ,thanks.

Exception in thread "main" java.lang.UnsatisfiedLinkError: no _CCFinderXLib in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at ccfinderx.CCFinderX.<clinit>(CCFinderX.java:18)
	at GemXMain.main(GemXMain.java:19)
make: *** [run] Error 1
